### ISSUE TITLE
Value with no children not returned in the hierarchy results

### ISSUE THREAD

**Issue by ptbrowne** [zazuko/cube-hierarchy-query#11]
Hi, I am debugging a bug from Veronique.
When displayed on visualize, one of the value from the hierarchy does not have any label.
I logged the query from cube-hierarchy-query and it is 

```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

DESCRIBE * WHERE {
    VALUES ( ?root )
{
( <https://ld.admin.ch/cube/dimension/ghg_emission_sectors_co2_ordinance_test3_gen_fab/1> )
( <https://ld.admin.ch/cube/dimension/ghg_emission_sectors_co2_ordinance_test3_gen_fab/2> )
( <https://ld.admin.ch/cube/dimension/ghg_emission_sectors_co2_ordinance_test3_gen_fab/3> )
}
    ?root ^skos:broader ?level1 .
      OPTIONAL { 
        ?level1 ^skos:broader ?level2 . 
        OPTIONAL {  ?level2 ^skos:broader ?level3 . } }
}
```

See https://s.zazuko.com/fkT8k3

Here, the value with no label is part of the roots `https://ld.admin.ch/cube/dimension/ghg_emission_sectors_co2_ordinance_test3_gen_fab/2>`, but it is not returned as part of the describe values since I think it has no value underneath, thus it does not respect the ?root ^skos:broader ?level1 predicate.

@**Tomasz Pluskiewicz (Zazuko)** Could we find a way so that it gets returned ? I tried to have the roots + the start in the describe but could not make it work. Adding fake roots that are not filtered by a predicate works https://s.zazuko.com/eZQ3WR but feels hacky.

**Comment by tpluscode** [comment]
An easy way could be to list the roots and all the levels explicitly instead of the `DESCRIBE *`

```diff
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

-DESCRIBE * WHERE {
+DESCRIBE 
+  <https://ld.admin.ch/cube/dimension/ghg_emission_sectors_co2_ordinance_test3_gen_fab/1>
+  <https://ld.admin.ch/cube/dimension/ghg_emission_sectors_co2_ordinance_test3_gen_fab/2>
+  <https://ld.admin.ch/cube/dimension/ghg_emission_sectors_co2_ordinance_test3_gen_fab/3>
+  ?level1 
+  ?level2 
+  ?level3 
+WHERE {
    VALUES ( ?root )
{
( <https://ld.admin.ch/cube/dimension/ghg_emission_sectors_co2_ordinance_test3_gen_fab/1> )
( <https://ld.admin.ch/cube/dimension/ghg_emission_sectors_co2_ordinance_test3_gen_fab/2> )
( <https://ld.admin.ch/cube/dimension/ghg_emission_sectors_co2_ordinance_test3_gen_fab/3> )
}
    ?root ^skos:broader ?level1 .
      OPTIONAL { 
        ?level1 ^skos:broader ?level2 . 
        OPTIONAL {  ?level2 ^skos:broader ?level3 . } }
}
```

**Comment by ptbrowne** [comment]
Sounds good, I will try then and make a PR. Or are you already on it ?

**Comment by tpluscode** [comment]
Not yet. Go ahead 💪
