### ISSUE TITLE
is sh:targetClass ignored in the query - eventhough it is displayed in the log

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-hierarchy-query#17]
Hi,

We are currently investigating why the hierarchy display is so slow in Visualize.
I am not sure if Visualize is using or not this cube-hierarchy-query, but if it does, maybe we found a bug/issue.

I tried it like this:
`DEBUG=SPARQL yarn example ./examples/hierarchy.ts --cube https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/1 --dimensionIri  https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/region --endpoint https://int.lindas.admin.ch/query
`
That dimension starts from the 26 cantons as root, and has a next level restricted to a specific class (regions for the Waldbrand use case), as you can [see here](https://gitlab.ldbar.ch/pipelines/bafu-gefahren-waldbrand-warnung/-/blob/develop/input/cube_base_triples_gefahren_waldbrand_warnung.ttl#L154).

I attach a .txt with the result of that run, where we see that the sh:targetClass seems recognized on line 76:
`?level1 a https://environment.ld.admin.ch/foen/gefahren-waldbrand/Region .`
But then you see that under each canton, all the municipalities are listed as well, with the regions.

Two questions:
- Is this a bug ? @tpluscode 
- Does Visualize rely on this to display hierarchies ? @ptbrowne 
if yes, as the filter do not display the municipalities but only the regions, is there a second filtering ?

Thanks
Fabian
[cube_hierarchy_query_fromZazuko_debug.txt](https://github.com/zazuko/cube-hierarchy-query/files/11545272/cube_hierarchy_query_fromZazuko_debug.txt)

**Comment by FabianCretton** [comment]
One more note about performance: with this SPARQL query I get that hiearchy in less than a second, compared to the 9 seconds of that run with Zazuko's library (to be noted that the slowness of that library gives similar times to the slowness we have in Visualize)
 https://s.zazuko.com/3fwC9ug

**Comment by Rdataflow** [comment]
> One more note about performance: with this SPARQL query I get that hiearchy in less than a second, compared to the 9 seconds of that run (similar to the slowness we have in Visualize) https://s.zazuko.com/3fwC9ug

Is the slow performance related to the SPARQL query? The query results in 389790 triples being fetched. Might this be related to duplicates?

**Comment by FabianCretton** [comment]
> > One more note about performance: with this SPARQL query I get that hiearchy in less than a second, compared to the 9 seconds of that run (similar to the slowness we have in Visualize) https://s.zazuko.com/3fwC9ug
> 
> Is the slow performance related to the SPARQL query? The query results in 389790 triples being fetched. Might this be related to duplicates?

Which SPARQL query, that returns 389790 triples, are you talking about ?

**Comment by tpluscode** [comment]
That is how many triples are fetched in the example. And yes, I think it does indicate a mistake in the generated query.

Where the `DESCRIBE` goes to list add the cantons, I think it should be replaced with `DESCRIBE ?root ?level1`. This way only those cantons actually associated with the regions are described and with less duplication

https://s.zazuko.com/3q6Hv6P

**Comment by FabianCretton** [comment]
Do you really use "DESCRIBE" instead of Select when you request the final data ?
IMHO, this is a mistake, and this is why the results are wrong: As you can see in the query you send (https://s.zazuko.com/3q6Hv6P), all the municipalities are returned (but they are not instances of <https://environment.ld.admin.ch/foen/gefahren-waldbrand/Region>) -> because of the DESCRIBE, they come out.
Morever, DESCRIBE is usually an implementation at the good will of the triple store provider.
Why don't you use a SELECT as the one I proposed for instance: https://s.zazuko.com/3fwC9ug

However, that DESCRIBE query seems to take much less time than the 9 seconds from the library, about one second roughly. Do you know why ?

**Comment by tpluscode** [comment]
> But then you see that under each canton, all the municipalities are listed as well, with the regions.

As you commented while I was typing this, the cause is indeed DESCRIBE.

We may restrict the query by the region type but what happens here is that by describing the cantons (with or without duplicates) we inevitable fetch all triples `?canton schema:containsPlace ?x`. Here, `?x` includes all municipalities as well as regions and the library does not distinguish between them once the data is loaded. 

To replace DESCRIBE with another query form (can be SELECT but I would go for CONSTRUCT to retain the "connectedness" of the graph) would require somehow selecting what properties to fetch for every level in hierarchy.

In your handcrafted query the properties are `schema:identifier`, `schema:alternateName`, `schema:name` and `schema:containsPlace` for the cantons, and `schema:identifier` and `schema:name` for the regions.

Without additional information we cannot know what query to generate. DESCRIBE removes that necessity by fetching everything at the expense of loading more than strictly necessary

> However, that DESCRIBE query seems to take much less time than the 9 seconds from the library, about one second roughly. Do you know why ?

I think that is mostly caused by duplicates served by the store.

**Comment by FabianCretton** [comment]
Well, all informations are available, I guess you know what to query (the ontology is defined, the values expected are defined, etc.., no ?)
I think the enduser is the person to serve, not the programmer. Especially when we see so  many performances problems.

But I still have my question: your DESCRIBE is less effective than my query. But however, the difference is not that big. 
So why does a run of your library take between 9 second to 18 seconds (I had this case this morning), compared to the 1 second of your DESCRIBE query. What does happen during the 8 other seconds ? 
Because this is just "unusable" for a user.
When I talk about 9 to 18 seconds, I talk about this run:
`DEBUG=SPARQL yarn example ./examples/hierarchy.ts --cube https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/1 --dimensionIri  https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/region --endpoint https://int.lindas.admin.ch/query `

**Comment by Rdataflow** [comment]
> That is how many triples are fetched in the example. And yes, I think it does indicate a mistake in the generated query.
> 
> Where the `DESCRIBE` goes to list add the cantons, I think it should be replaced with `DESCRIBE ?root ?level1`. This way only those cantons actually associated with the regions are described and with less duplication
> 
> https://s.zazuko.com/3q6Hv6P

While the query proposed above  is way better (33012 triple results in ~2.2s initially)
yet it serves more than the totally expected 4296 resulting triples. i.e.
- https://s.zazuko.com/3kXcyMS resulting in 1562 triples within 0.2s 
- https://s.zazuko.com/3pUmUwR resulting in 2734 triples within 0.2s
and takes it's extra amount of time compared the two quick queries within 0.2s.

Observing this I guess there are possibilities to further optimize the performance as well as the amount of results 😄

**Comment by tpluscode** [comment]
> Observing this I guess there are possibilities to further optimize the performance as well as the amount of results 😄

Absolutely! As @FabianCretton says, that would require removing DESCRIBE from the picture but in a ways that works for every hierarchy. I missed the obvious answer before, which is to add on open-ended `?s ?p ?o` pattern to any given hierarchy level. The only missing piece here is to exclude the hierarchy path so that the unnecessary municipalities are omitted. Here's my rendition which was partially generated and I should adjust the generator to be able to provide this exact query: https://s.zazuko.com/FSkqgm

**Comment by FabianCretton** [comment]
Hi,

I see that you want to optimize a generic query and this seems good for sure (another way seems to simply first query about the hierarchy itself and then generate a specific query as SELECT). I let you deal with that the way you want, as it seems it is not the bottleneck here.

With this issue I am asking why a query that takes about 1 second (no matter if it is the optimized query or not), does take 9 to 18 seconds with the lib, as explained [here above](https://github.com/zazuko/cube-hierarchy-query/issues/17#issuecomment-1562659317).

Can you comment about this, and maybe explain me if that questioning is totally irrelevant ?
Thanks and have a nice Friday

**Comment by tpluscode** [comment]
The query is already generic, in that it is being generated and must work for any hierarchy.

> I let you deal with that the way you want, as it seems it is not the bottleneck here.

Actually, I do think that, in large part, `DESCRIBE` is the bottleneck as it returns duplicated results. Too many unnecessary triples by a factor of 10. I find that on first run the query alone takes some 8 seconds which decreases to 5-6 on subsequent executions while query plan cache is fresh. In practice, 300k results is a significant number which further leads to unnecessary overhead needed to parse put that in memory and further process in library and consumer code. All that likely adds up to become a measurable moderator.

**Comment by FabianCretton** [comment]
Thanks for the feed-back.
Which query is taking 8 seconds, can you send me link to the Yasgui to run it ? Because the ones I tried, with Describe, did take around a second.

Sometimes, doing 2 queries, a first one to understand the dataset, the second one to write a more specific query, is a good way to go, don't you think ?

**Comment by FabianCretton** [comment]
As an example (not the exact case here but still interesting), here is an optimization that I proposed a year ago, for the Cube Designer, with a significant improvement in performance for the large cubes:
https://github.com/zazuko/cube-creator/issues/1212

It has never been discussed or implemented though, but would have improved the user experience from a 40 seconds wait to 10 seconds....(having just discarded my proposal without any explanation, being around one hour work for a programmer, is why you might hear my frustration sometimes...)

**Comment by tpluscode** [comment]
> Which query is taking 8 seconds, can you send me link to the Yasgui to run it ?

The query which the library generates right now https://s.zazuko.com/2yAPs1E. I just checked yasgui, took 7.2 seconds and downloaded 42 MB  

> Sometimes, doing 2 queries, a first one to understand the dataset, the second one to write a more specific query, is a good way to go, don't you think ?

Yes, it does help sometimes but I have had mixed results, to be honest. Anyway, I don't necessarily see it as required in this case

**Comment by FabianCretton** [comment]
Thanks for the query.
Well, it seems that the Describe of the 26 cantons is the slow part in the query, and resulting in so many triples.

Anyway, I don't want to bother you with my opinion, but this is just unusable right now (I provided a very fast query if it could interest you somehow). I also have quiet some experience with SPARQL queries and very often needed query writing optimization.

Please keep @Rdataflow  Thomas  and myself informed if you can do something about it or if we should find other solutions.
Thanks

**Comment by Rdataflow** [comment]
> > Observing this I guess there are possibilities to further optimize the performance as well as the amount of results 😄
> 
> Absolutely! As @FabianCretton says, that would require removing DESCRIBE from the picture but in a ways that works for every hierarchy. I missed the obvious answer before, which is to add on open-ended `?s ?p ?o` pattern to any given hierarchy level. The only missing piece here is to exclude the hierarchy path so that the unnecessary municipalities are omitted. Here's my rendition which was partially generated and I should adjust the generator to be able to provide this exact query: https://s.zazuko.com/FSkqgm

would be great you adjust the query generator in such a way 👍 
nb: tiny tech detail
```
  { 
    ?resource1 schema:containsPlace ?resource2.
    ?resource2 a <https://environment.ld.admin.ch/foen/gefahren-waldbrand/Region> .
  }
  UNION
  {
    ?resource1 schema:containsPlace ?resource2.
    ?resource2 a <https://environment.ld.admin.ch/foen/gefahren-waldbrand/Region> .
	?resource2 ?l1p ?resource3.
  }
```
this would lead to dups for `?resource1 schema:containsPlace ?resource2.`
- but it could be tweaked i.e. like this... https://s.zazuko.com/36ohTM8  (total of 4296 results in ~0.2s)
- or if we intentionally omit irrelevant containsPlace even better like this ... https://s.zazuko.com/r7SMMQ (2145 results in <0.2s)

@tpluscode can you adjust the generator in this lib in such an optimized manner and release a new version? this will help to realize vast performance improvements 🚀 so @ptbrowne can profit an gain lightspeed

cc @claudiodigallo @FabianCretton

**Comment by tpluscode** [comment]
Thank you for the observation @Rdataflow. I am aware of the remaining redundancy. I will try to further improve based on your suggestion.

Not to delay any further, I would like to proceed with the best I've got so far which already should be noticeable improvement. Code changes are now ready and I will roll out v2 of the library soon

**Comment by Rdataflow** [comment]
@tpluscode yes I prepfer you deploy asap
and thanks a lot for your helpful work 🚀

**Comment by tpluscode** [comment]
@ptbrowne v2 published. please give it a go

**Comment by ptbrowne** [comment]
Thanks @tpluscode , I've created a ticket on our side, since there seems to be a breaking change, I guess we would need to adapt a bit our code. Do you have any example on how the code would change client side ?

**Comment by tpluscode** [comment]
CONSTRUCT can technically return different results than DESCRIBE but TBH, I do not think you'll have any issues nor code changes needed @ptbrowne
