### ISSUE TITLE
Example with `rdf-cube-view-query`

### ISSUE THREAD

**Issue by ptbrowne** [zazuko/cube-hierarchy-query#2]
I am trying to make `rdf-cube-view-query` work with `cube-hierarchy-query`, would you have any pointer (🙃) on how to do that ?

I load a cube via 

```
  const source = new Source({
    endpointUrl: SPARQL_ENDPOINT,
    queryOperation: "postUrlencoded",
  })
  const cube = await source.cube(iri);
```

Next I would like to 

* Find all hierarchies from this cube
* Fetch the values from the hierarchies

I am going to continue making it work but if you have any advice, please let me know, I will report my progress here.

**Comment by tpluscode** [comment]
I think you're already set here @ptbrowne?

> Fetch the values from the hierarchies

This is one got implemented in #9 

> Find all hierarchies from this cube

And similarly to what you do already, this will find all hierarchies

```
const hierarchy = cube.ptr
    .any()
    .has(meta.inHierarchy)
    .out(meta.inHierarchy)
    .toArray()
```
