### ISSUE TITLE
Questioning about performance of levels meta:nextInHierarchy defined with sh:inversePath

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-hierarchy-query#21]
Regarding the Waldbrand cube and the hierarchy of Cantons/Fire warning regions (for which we opened that former issue #17)
We now observe in Visualize a performance difference if we describe the meta:nextInHierarchy from root cantons to fire warning regions (schema:containsPlace) compared to the use of sh:inversePath schema:containedInPlace.
Both can be seen [here](https://gitlab.ldbar.ch/pipelines/bafu-gefahren-waldbrand-warnung/-/blob/develop/input/cube_base_triples_gefahren_waldbrand_warnung.ttl?ref_type=heads#L152) - containedInPlace currently commented out.

When trying out the [graphQL calls with timing (at the end of this message), the difference is about 10X (around 0.2 for the containsPlace, 2 seconds for the containedInPlace).

Comparing the results with two SPARQL queries that create the hierarchy, I get very similar run times, less than 0.5 second:
containsPlace: https://s.zazuko.com/3fwC9ug
containedInPlace: https://s.zazuko.com/fiDb8t

Can you find a reason for this performance difference ?
Thanks

------------------------------------
time curl 'https://int.visualize.admin.ch/api/graphql'  -H 'x-visualize-cache-control: no-cache' --data-raw $'{"query":"query DimensionHierarchy($sourceType: String\u0021, $sourceUrl: String\u0021, $locale: String\u0021, $cubeIri: String\u0021, $dimensionIri: String\u0021) {\\n  dataCubeByIri(\\n    iri: $cubeIri\\n    sourceType: $sourceType\\n    sourceUrl: $sourceUrl\\n    locale: $locale\\n  ) {\\n    dimensionByIri(\\n      iri: $dimensionIri\\n      sourceType: $sourceType\\n      sourceUrl: $sourceUrl\\n    ) {\\n      ...hierarchyMetadata\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\\nfragment hierarchyMetadata on Dimension {\\n  hierarchy(sourceType: $sourceType, sourceUrl: $sourceUrl) {\\n    ...hierarchyValueFields\\n    children {\\n      ...hierarchyValueFields\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\\nfragment hierarchyValueFields on HierarchyValue {\\n  value\\n  dimensionIri\\n  depth\\n  label\\n  alternateName\\n  hasValue\\n  position\\n  identifier\\n}\\n","operationName":"DimensionHierarchy","variables":{"cubeIri":"https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/1","dimensionIri":"https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/region","sourceType":"sparql","sourceUrl":"https://int.lindas.admin.ch/query","locale":"de"}}' -o /dev/null

**Comment by FabianCretton** [comment]
@tpluscode To be noted that this test was done with the GraphQL, and not directly with the new version of the lib, as you can see.  
This is because I had some problems installing the new version of the lib on my VM, and we could talk about this if you want me to test the lib itself.
However, I raise this issue to ask about your opinion.
Thanks

**Comment by sam-e-ch** [comment]
The SPARQL queries generated using the command
```
DEBUG=SPARQL yarn example ./examples/hierarchy.ts --cube https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/1 --dimensionIri  https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/region --endpoint https://int.lindas.admin.ch/query
```
is ~2.5 times as fast compared to query generated for the cube `https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung-contained-in-place/1` and returns ~4500 vs. ~35000 results.
(See https://s.zazuko.com/QuSrCg vs https://s.zazuko.com/2U645Qm)

So there may be some potential in optimizing the SPARQL queries.

cc @rdataflow

**Comment by tpluscode** [comment]
In the case of direct hierarchy path I add the additional filter `FILTER((!((?resource5 = schema:containsPlace))))`. This is to overcome one problem discussed in #17, where too many results were returned despite the class constraint

This filter does not work when the hierarchy is defined with an inverse property because it needs to filter on the direct relation. Without knowing what is the direct equivalent of the inverse path I do not yet see how to filter it effectively

**Comment by CDiGallo** [comment]
I am afraid.
Pipelines in TEST do not work, the cubes do not load and int.visualize has an out of memory exception. And this is just today. As this  issue only affects one cube, this is not a priority right now.

From our perspective, generally Performance is good enough in visualize. We need to work on stability.

The solution now is not ideal. We will have look at this, if other people need to add maps in the hierarchies.

Thanks everyone for their work, it has greatly improved performance and we will come back to this issue.
