### ISSUE TITLE
Improve query time of some queries

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-hierarchy-query#34]
To  repeat VALUES ... (incl. chains of ?resource1 <pred1> ?resourceN . ... where N unequal 1) to speed some slow queries by factors on each hierarchy level (at the place where the `group.joins` were)

```shell
DEBUG=SPARQL yarn example ./examples/hierarchy.ts --endpoint https://ld.admin.ch/query --cube  https://environment.ld.admin.ch/foen/ubd000502/4 --dimensionIri https://environment.ld.admin.ch/foen/ubd000502/sektorid
```

w/ patch: 0.5s
w/o patch: 5.4 s

patch for this query
```diff
--- query.slow
+++ query.fixed
@@ -116,6 +116,8 @@
      }
      UNION
      {
+       VALUES (?resource1) { (<https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/1>) (<https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/2>) (<https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/3>) }
+       ?resource11 skos:broader ?resource1 .
        {
          ?resource21 skos:broader ?resource11 .
        }
@@ -165,6 +167,9 @@
          }
          UNION
          {
+           VALUES (?resource1) { (<https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/1>) (<https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/2>) (<https://environment.ld.admin.ch/vocabulary/ghg_emission_sectors_co2_ordinance/3>) }
+           ?resource11 skos:broader ?resource1 .
+           ?resource21 skos:broader ?resource11 .
            {
              ?resource31 skos:broader ?resource21 .
            }

```
- see [query.slow](https://github.com/zazuko/cube-hierarchy-query/files/14327711/query.slow.txt)
- see [query.fixed](https://github.com/zazuko/cube-hierarchy-query/files/14327712/query.fixed.txt)

_Originally posted by @Rdataflow in https://github.com/zazuko/cube-hierarchy-query/issues/31#issuecomment-1951844771_

**Comment by CDiGallo** [comment]
Hey @tpluscode 
Is this already the new 'finished' (not tested yet) patch, or is this the issue to not forget, how it should be made?

**Comment by tpluscode** [comment]
Well yes, the issue is to not forget about the problem. The fix may be as proposed or slightly different. We'll see

**Comment by Rdataflow** [comment]
> Well yes, the issue is to not forget about the problem. The fix may be as proposed or slightly different. We'll see

of course you are free to adapt the pattern ... if only you ensure the new pattern fits all the available hierarchies to fetch rapidly within subsecond. 😄 
(most hierarchies do so - except for some cases i.e.  `DEBUG=SPARQL yarn example ./examples/hierarchy.ts --endpoint https://ld.admin.ch/query --cube  https://environment.ld.admin.ch/foen/ubd000502/4 --dimensionIri https://environment.ld.admin.ch/foen/ubd000502/sektorid`)
