### ISSUE TITLE
migrate `hasHierarchy` -> `inHierarchy` to conform the spec

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/cube-hierarchy-query#6]
https://github.com/zazuko/cube-hierarchy-query/blob/9038cd17dfa644ce92f75edfd2944d25884db596/examples/children.ts#L26-L31

see zazuko/cube-creator#1243

cc @ortnever @zellersabine @pierredumas

**Comment by tpluscode** [comment]
Fixed as of `v1.0.0-pre.2`
